import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Drosera AI",
  description: "Generated by Next.js",
};

import { inter } from "./ui/fonts";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased h-vh`}>{children}</body>
    </html>
  );
}
